config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :users do
    put 'follow', on: :member
    put 'unfollow', on: :member
  end

  resources :messages, only: [:index, :show, :create, :destroy]
  
  resources :notifications, only: [:update, :fresh] do
    get 'fresh', on: :collection
  end

  resources :posts, except: [:edit, :update, :new] do
    get 'fresh', on: :collection
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users do
        put 'follow', on: :member
        put 'unfollow', on: :member
      end
      resources :posts, except: [:edit, :update, :new] do
        get 'fresh', on: :collection
      end
      resources :messages, only: [:index, :show, :create, :destroy]
    end
  end

  root 'posts#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :from, foreign_key: "from_id", class_name: "User"
  belongs_to :to, foreign_key: "to_id", class_name: "User"

  validates :from, :to, :description, presence: true

  scope :unread, -> { where(read: false).order(id: :desc) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  before_action :authenticate_user!

  def update
    @notification = Notification.find(params[:id])
    @notification.update(notification_params)
    respond_to do |format|
      format.html { redirect_to @notification.from }
    end
  end

  def fresh
    @notifications = current_user.notifications.unread.where("notifications.id > ?", params[:after].to_i)
    @count = current_user.notifications.unread.count
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:description, :to_id, :read)
    end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li class="notification" data-id="<%= notification.id %>">
  <%= link_to notification.description, notification_path(notification, :notification => { read: true }), method: :put %>
</li>

app/views/notifications/fresh.js.erb
addNotifications("<%= j render(@notifications) %>")
<% if @count > 0 %>
  $("#notifications_badge").html("<%= @count %>");
  $("#notifications_badge").removeClass("hide");
  $("#notifications_empty").addClass("hide");
<% else %>
  $("#notifications_badge").addClass("hide");
  $("#notifications_empty").removeClass("hide");
<% end %>