config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :users do
    put 'follow', on: :member
    put 'unfollow', on: :member
  end

  resources :messages, only: [:index, :show, :create, :destroy]
  
  resources :notifications, only: [:update, :fresh] do
    get 'fresh', on: :collection
  end

  resources :posts, except: [:edit, :update, :new] do
    get 'fresh', on: :collection
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users do
        put 'follow', on: :member
        put 'unfollow', on: :member
      end
      resources :posts, except: [:edit, :update, :new] do
        get 'fresh', on: :collection
      end
      resources :messages, only: [:index, :show, :create, :destroy]
    end
  end

  root 'posts#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  before_create :set_token

  has_many :follower_friendships, foreign_key: :followee_id, class_name: "Friendship"
  has_many :followers, through: :follower_friendships, source: :follower

  has_many :followee_friendships, foreign_key: :follower_id, class_name: "Friendship"
  has_many :followees, through: :followee_friendships, source: :followee


  has_many :messages, foreign_key: :to_id
  has_many :notifications, foreign_key: :to_id
  has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :username, format: { with: /\A(\w|\.)+\Z/ }, uniqueness: true, presence: true
  validates :email, email: true, uniqueness: true, presence: true

  self.per_page = 20
  
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  def placeholder_avatar(size=200)
    "http://api.adorable.io/avatars/#{size}/#{username}"
  end

  def follow(another_user)
    another_user.followers << self
    notification = Notification.new
    notification.to = another_user
    notification.from = self
    notification.description = "You have a new follower: @#{self.username}."
    notification.read = false
    notification.save
  end

  def unfollow(another_user)
    another_user.followers.delete(self)
  end

  def follows?(another_user)
    followees.where(id: another_user.id).exists?
  end

  def set_token
    return if token.present?
    self.token = generate_token
  end

  def generate_token
    SecureRandom.uuid.gsub(/\-/,'')
  end

  def to_s
    username
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  respond_to :json
  skip_before_filter :verify_authenticity_token

  def index
    user = User.find_by(token: params[:token])
    if user.nil?
      message = { message: 'User not found' }
      render json: message.to_json, status: :unauthorized
      return
    elsif params.has_key?(:q)
      search_params = {}
      search_params[:name_or_username_or_email_cont] = params[:q]
      users = User.ransack(search_params).result.order(:username)
    else
      users = User.all
    end
    render json: users.to_json, status: :ok
  end

  def follow
    user = User.find_by(token: params[:token])
    if user.nil?
      message = { message: 'User not found' }
      render json: message.to_json, status: :unauthorized
      return  
    else
      another_user = User.find(params[:id])
      if another_user.nil?
        message = { message: 'Folowee not found.' }
        render json: message.to_json, status: :bad_request
      else
        user.follow(another_user)
        render json: user.to_json, status: :ok
      end
    end
  end

  def unfollow
    user = User.find_by(token: params[:token])
    if user.nil?
      message = { message: 'User not found' }
      render json: message.to_json, status: :unauthorized
      return  
    else
      another_user = User.find(params[:id])
      if another_user.nil?
        message = { message: 'Folowee not found.' }
        render json: message.to_json, status: :bad_request
      else
        user.unfollow(another_user)
        render json: user.to_json, status: :ok
      end
    end
  end

  def show
    user = User.find_by(token: params[:token])
    if user.nil?
      message = { message: 'User not found' }
      render json: message.to_json, status: :unauthorized
      return
    else
      found_user = User.find(params[:id])
    end
    render json: found_user.to_json, status: :ok
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :follow, :update, :unfollow, :destroy]

  # GET /users
  # GET /users.json
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.page(params[:page]).order(:username)
    @message = Message.new
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @message = Message.new
    @message.to = @user
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to :back, notice: 'Photo updated successfully.' }
        format.json { render :show, status: :ok, location: @flag }
      else
        @post = Post.new
        @posts = Post.timeline(current_user).page(params[:page])
        @user_avatar = @user
        format.html { render "posts/index" }
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  def follow
    respond_to do |format|
      if @user.id == current_user.id
        format.html { redirect_to @user, notice: 'You cannot follow yourself.' }
        format.json { render :show, status: :ok, location: @user }
      elsif current_user.follow(@user)
        format.html { redirect_to @user, notice: "You are following @#{@user.username}." }
        format.json { render :show, status: :ok, location: @user }
      end
    end
  end

  def unfollow
    respond_to do |format|
      if @user.id == current_user.id
        format.html { redirect_to @user, notice: "You cannot unfollow yourself" }
        format.json { render :show, status: :ok, location: @user }
      elsif current_user.unfollow(@user)
        format.html { redirect_to @user, notice: "You unfollowed @#{@user.username}." }
        format.json { render :show, status: :ok, location: @user }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatar.html.erb
<% if user.avatar_file_name.nil? %>
  <img src="<%= user.placeholder_avatar %>" width="200" height="200" class="img-thumbnail">
<% else %>
  <%= image_tag user.avatar.url(:square), class: 'img-thumbnail' %>
<% end %>

app/views/users/_follow_link.html.erb
<% if user.id != current_user.id %>
  <% if current_user.follows?(user) %>
    <%= link_to 'Unfollow', unfollow_user_path(user), method: :put, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Follow', follow_user_path(user), method: :put, class: 'btn btn-success' %>
  <% end %>
  <button type="button" class="btn btn-info" data-toggle="modal" data-target="#message_modal" data-to_id="<%= user.id%>" data-name="<%= user.name %>">
    Message
  </button>
  <%= render 'messages/form' %>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :username %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= div_for user, data: { id: user.id } do %>
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-2">
          <%= render partial: 'users/avatar', locals: { user: user } %>
        </div>
        <div class="col-md-6">
          <h3><%= user.name %></h3>
          <%= link_to display_author(user), user %>
        </div>
        <div class="col-md-4">
          <div class="btn-group pull-right" role="group">
            <% if current_user != user %>
              <% if current_user.follows?(user) %>
                <%= link_to 'Unfollow', unfollow_user_path(user), method: :put, class: 'btn btn-danger' %>
              <% else %>
                <%= link_to 'Follow', follow_user_path(user), method: :put, class: 'btn btn-success' %>
              <% end %>
              <button type="button" class="btn btn-info" data-toggle="modal" data-target="#message_modal" data-to_id="<%= user.id%>" data-name="<%= user.name %>">
                Message
              </button>
            <% end %>
          </div>
        </div>
      </div>  
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= search_form_for @q, html: { class: 'form-horizontal' },
                        wrapper: :horizontal_form do |f| %>
  <div class="row">
    <div class="col col-md-10">
      <%= f.input :name_or_username_or_email_cont,
                  label: 'Search users',
                  placeholder: 'By name, username, email...', as: :string %>
    </div>
    <div class="col col-md-2">
      <%= f.submit "Filter", class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

<%= render @users %>
<%= will_paginate @users %>
<%= render 'messages/form' %>

app/views/users/show.html.erb
<h1>Tweets de <%= @user.name %> <small>@<%= @user.username %></small></h1>

<%= render partial: 'users/follow_link', locals: { user: @user, send_message: true } %>

<br>

<%= render @user.posts %>