config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :users do
    put 'follow', on: :member
    put 'unfollow', on: :member
  end

  resources :messages, only: [:index, :show, :create, :destroy]
  
  resources :notifications, only: [:update, :fresh] do
    get 'fresh', on: :collection
  end

  resources :posts, except: [:edit, :update, :new] do
    get 'fresh', on: :collection
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users do
        put 'follow', on: :member
        put 'unfollow', on: :member
      end
      resources :posts, except: [:edit, :update, :new] do
        get 'fresh', on: :collection
      end
      resources :messages, only: [:index, :show, :create, :destroy]
    end
  end

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :user, :description, presence: true
  validates :description, length: { maximum: 144 }

  self.per_page = 20

  scope :timeline, ->(user) { Post.joins("LEFT JOIN friendships ON friendships.followee_id = posts.user_id")
                                  .joins("LEFT JOIN users ON users.id = friendships.follower_id")
                                  .where("users.id = ? OR posts.user_id = ?", user.id, user.id)
                                  .order("posts.id DESC") }

  def ==(another_post)
    id == another_post.id
  end

end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  respond_to :json
  skip_before_filter :verify_authenticity_token

  def index
    user = User.find_by(token: params[:token])
    if user.nil?
      posts = Post.order(id: :desc)
    else
      posts = Post.timeline(user)
    end
    render json: posts.to_json, status: :ok
  end

  def fresh
    user = User.find_by(token: params[:token])
    puts params.inspect
    if !params.has_key?(:after)
      message = { message: 'Required parameter *after* was not passed.' }
      render json: message.to_json, status: :bad_request
      return  
    elsif user.nil?
      posts = Post.timeline(current_user).where("posts.id > ?", params[:after].to_i)
    else
      posts = Post.where("id > ?", params[:after].to_i).order(id: :desc)
    end
    render json: posts.to_json, status: :ok
  end

  def show
    user = User.find_by(token: params[:token])
    if user.nil?
      message = { message: 'User not found' }
      render json: message.to_json, status: :unauthorized
      return
    else
      post = Post.find(params[:id])
    end
    render json: post.to_json, status: :ok
  end

  def destroy
    user = User.find_by(token: params[:token])
    if user.nil?
      message = { message: 'User not found' }
      render json: message.to_json, status: :unauthorized
      return
    else
      post = Post.find(params[:id])
      if post.user.id == user.id && post.destroy
        render json: post.to_json, status: :ok
      else
        render json: message.to_json, status: :forbidden
      end
    end
  end  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :fresh]
  before_action :set_post, only: [:show, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if user_signed_in?
      @post = Post.new
      @posts = Post.timeline(current_user).page(params[:page])
    else
      @posts = Post.page(params[:page]).order(id: :desc)
    end
  end

  def fresh
    if user_signed_in?
      @posts = Post.timeline(current_user).where("posts.id > ?", params[:after].to_i)
    else
      @posts = Post.where("id > ?", params[:after].to_i).order(id: :desc)
    end
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to root_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        @posts = Post.timeline(current_user).page(params[:page])
        format.html { render :index }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    respond_to do |format|
      if @post.user.id == current_user.id && @post.destroy
        format.html { redirect_to root_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to root_url, notice: 'Post was not destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :description)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="clearfix">
<%= simple_form_for(@post) do |f| %>

  <div class="form-inputs">
    <%= f.input :description, as: :text, placeholder: 'What is happening?', autofocus: true, hint: '144' %>
  </div>

  <div class="form-actions pull-right">
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
      <i class="glyphicon glyphicon-send"></i> Tweet
    <% end %>
  </div>
<% end %>
</div>

app/views/posts/_post.html.erb
<%= div_for post, data: { id: post.id } do %>
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-2">
          <%= render partial: 'users/avatar', locals: { user: post.user } %>
        </div>
        <div class="col-md-10">
          <p>
            <strong><%= link_to "@#{post.user.username}", post.user %></strong>
            <small><%= time_ago_in_words(post.created_at) %> ago</small>
          </p>
          <p>
            <%= post.description %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/fresh.js.erb
addPosts("<%= j render(@posts) %>");

app/views/posts/index.html.erb
<%= render 'form' if user_signed_in? %>

<br>

<div class="alert alert-info" id="show_posts" style="display: none">
  You have new tweets. <a href="#">Show tweets</a>
</div>

<%= content_tag :div, id: "posts", data: { url: fresh_posts_url } do %>
  <%= render @posts %>
<% end %>

<%= will_paginate @posts %>

app/views/posts/index.js.erb
$('#posts').append('<%= escape_javascript render(@posts) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@posts) %>');

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %>