config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :users do
    put 'follow', on: :member
    put 'unfollow', on: :member
  end

  resources :messages, only: [:index, :show, :create, :destroy]
  
  resources :notifications, only: [:update, :fresh] do
    get 'fresh', on: :collection
  end

  resources :posts, except: [:edit, :update, :new] do
    get 'fresh', on: :collection
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users do
        put 'follow', on: :member
        put 'unfollow', on: :member
      end
      resources :posts, except: [:edit, :update, :new] do
        get 'fresh', on: :collection
      end
      resources :messages, only: [:index, :show, :create, :destroy]
    end
  end

  root 'posts#index'

end

app/views/layouts/_login.html.erb
<div class="page-header">
  <h2>Welcome to Fake Twitter</h2>
</div>
<%= link_to "Login", new_user_session_path, class: 'btn btn-success', role: :button %>
  <span>Or</span>
<%= link_to "Sign up", new_user_registration_path, class: 'btn btn-default' %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Fake Twitter', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= active_class('posts','index') %>"><%= link_to 'Home', posts_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Notifications  
              <span class="badge <%= hide_when(current_user.notifications.unread.count == 0) %>" id="notifications_badge">
                <%= current_user.notifications.unread.count %>
              </span>
            </a>
            <ul class="dropdown-menu" id="notifications" data-url="<%= fresh_notifications_path %>">
              <%= render current_user.notifications.unread %>
              <li class="<%= hide_when(current_user.notifications.unread.count > 0) %>" id="notifications_empty">
                <a href="#">You have no notifications now.</a>
              </li>
            </ul>
          </li>
          <li class="<%= active_class('messages','index') %>"><%= link_to 'Messages', messages_path %></li>
          <li class="<%= active_class('users','index') %>"><%= link_to 'Users', users_path %></li>
        <% end %>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit account', edit_user_registration_path %></li>
              <li></li>
              <li></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_profile.html.erb
<div class="page-header">
  <a href="#" data-toggle="modal" data-target="#photo">
    <%= render partial: 'users/avatar', locals: { user: current_user } %>
  </a>
  <h2><%= current_user.name %> <small><%= link_to "@#{current_user.username}", current_user %></small></h2>
</div>
<p><span class="badge"><%= current_user.posts.count %></span> tweets</p>
<p><span class="badge"><%= current_user.followers.count %></span> followers</p>
<p><span class="badge"><%= current_user.followees.count %></span> following</p>

<%= simple_form_for(@user_avatar, multipart: true) do |f| %>
  <div class="modal fade" id="photo">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Change photo</h4>
        </div>
        <div class="modal-body">
          <div class="form-inputs">
            <%= f.input :avatar, required: true %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.button :submit, value: 'Send', class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fake Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navbar' %>
  </header>

  <div class="row">
    <div class="col-md-3 col-md-offset-1">
      <% if user_signed_in? %>
        <%= render 'layouts/profile' %>
      <% else %>
        <%= render 'layouts/login' %>
      <% end %>
    </div>
  	<div class="col-md-7">
    	<%= render 'layouts/messages' %>
    	<%= yield %>
  	</div>
  </div>
  <script type="text/javascript">
    $('#message_modal').on('show.bs.modal', function(event) {
      var button, modal, name, to_id;
      button = $(event.relatedTarget);
      name = button.data('name');
      to_id = button.data('to_id');
      modal = $(this);
      modal.find('.modal-title').text("New message to " + name);
      $('#message_to_id').val(to_id);
      return $('#message_description')[0].focus();
    });
  </script>
</body>
</html>